# Generated by Django 4.2.6 on 2023-11-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcl',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Все размеры в наличии', 'Все размеры в наличии')], default=('S', 'S'), max_length=25),
        ),
    ]
