# Generated by Django 4.2.6 on 2023-11-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_alter_productcl_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcl',
            name='sex',
            field=models.CharField(choices=[('Не указано', 'Не указано'), ('men', 'Мужские'), ('Женские', 'Женские'), ('Универсальные', 'Универсальные'), ('Детские', 'Детские')], default=('Не указано', 'Не указано'), max_length=100),
        ),
    ]
