# Generated by Django 4.2.6 on 2023-11-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0003_alter_productcl_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcl',
            name='sex',
            field=models.CharField(choices=[('Not Indicated', 'Not Indicated'), ('Men', 'Men'), ('Women', 'Women'), ('Uni', 'Uni'), ('Kids', 'Kids')], default=('Not Indicated', 'Not Indicated'), max_length=100),
        ),
        migrations.AlterField(
            model_name='productcl',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('All sizes available', 'All sizes available')], default=('S', 'S'), max_length=25),
        ),
    ]
