# Generated by Django 4.2.6 on 2023-11-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0004_alter_productcl_sex_alter_productcl_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercl',
            name='address',
            field=models.CharField(max_length=40),
        ),
    ]
