# Generated by Django 4.2.6 on 2023-11-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0005_alter_customercl_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcl',
            name='sex',
            field=models.CharField(choices=[('Not Indicated', 'Not Indicated'), ('men', 'Men'), ('women', 'Women'), ('Uni', 'Uni'), ('Kids', 'Kids')], default=('Not Indicated', 'Not Indicated'), max_length=100),
        ),
    ]
