# Generated by Django 4.2.6 on 2023-11-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0007_alter_productcl_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercl',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloth.customercl'),
        ),
        migrations.AlterField(
            model_name='ordercl',
            name='products',
            field=models.ManyToManyField(null=True, to='cloth.productcl'),
        ),
    ]
