# Generated by Django 4.2.6 on 2023-11-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0008_alter_ordercl_customer_alter_ordercl_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercl',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cloth.customercl'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercl',
            name='products',
            field=models.ManyToManyField(to='cloth.productcl'),
        ),
    ]
