# Generated by Django 4.2.6 on 2023-11-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0009_alter_ordercl_customer_alter_ordercl_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcl',
            name='sex',
            field=models.CharField(choices=[('Not Indicated', 'Not Indicated'), ('men', 'men'), ('women', 'women'), ('uni', 'uni'), ('kids', 'kids')], default=('Not Indicated', 'Not Indicated'), max_length=100),
        ),
    ]
