# Generated by Django 4.2.6 on 2023-10-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('cost', models.SmallIntegerField(verbose_name='Цена книги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
